4: User update functionality implemented
nemiro54/CorgiApp pull request #12
Opened 2022-12-29 18:14 UTC by nemiro54

# PR Details

* added the ability to update User details

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-12-29 18:58 UTC, belkvch submitted a review, later dismissed

2022-12-29 18:58 UTC, belkvch commented on src/main/java/com/andersen/corgiapp/servlet/EditUserServlet.java
> +    private static final Logger log = LoggerFactory.getLogger(SaveServlet.class);
Change to getLogger(EditUserServlet.class)

2022-12-29 18:58 UTC, belkvch commented on src/main/java/com/andersen/corgiapp/servlet/EditUserServlet.java
> +            response.sendRedirect(USER_LIST_PATH);
I think better solution is using "sendRedirect" for href "/users/details?id=${user.id}":
User details -> User edit -> User detail

2022-12-30 07:35 UTC, myo044 approved these changes
Everything looks fine

2022-12-30 07:45 UTC, MerakseS approved these changes

2022-12-30 07:45 UTC, MerakseS commented on src/main/java/com/andersen/corgiapp/servlet/EditUserServlet.java
> +        request.getRequestDispatcher(USER_EDIT_PATH).forward(request, response);
- В форму должен передаваться пользователь, чтобы можно было изменять его данные

2022-12-30 07:45 UTC, MerakseS commented on src/main/java/com/andersen/corgiapp/servlet/EditUserServlet.java
> +    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
Должен быть отдельный сервлет для отображения формы обновления, так как если пользователь не пройдет валидацию, то форма ему не вернется.

2022-12-30 07:45 UTC, MerakseS commented on src/main/webapp/WEB-INF/jsp/editUser.jsp
> +  <input id="age" name="age" type="number" min="0" value="0">
Здесь поля ввода должны заполняться данными пользователя, которые мы хотим изменить

2022-12-30 07:45 UTC, MerakseS commented on src/main/webapp/WEB-INF/jsp/editUser.jsp
> +    <button>Cancel</button>
С этой кнопкой баг. Замени на `<input type="button" value="Cancel"/>`

2022-12-30 07:45 UTC, MerakseS commented on src/main/webapp/WEB-INF/jsp/editUser.jsp
> +  <a href="<c:url value="/users"/> ">
Тут тоже возвращение на /details

2022-12-30 07:59 UTC, MerakseS requested changes
Нечаянно поставил апрув(

2022-12-30 10:13 UTC, myo044 requested changes

2022-12-30 10:22 UTC, MerakseS submitted a review, later dismissed

2022-12-30 11:07 UTC, MerakseS commented
А откуда вызывается форма редактирования?

2022-12-30 11:23 UTC, myo044 commented
> А откуда вызывается форма редактирования?

У нас отдельная таска на это. Лучше, наверное, в этом ПР сделать её

2022-12-30 12:55 UTC, jokindy approved these changes
Nice work

2022-12-30 12:56 UTC, MerakseS approved these changes

2022-12-30 12:56 UTC, myo044 approved these changes
Well done

2022-12-30 12:56 UTC, merged